package au.com.new1step.apps.vip.ws.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-12-05T16:44:28.371+11:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "IFEntityServiceService", 
                  wsdlLocation = "file:/home/andy/workspaces/alw-web-apps/dongnanVipService/src/main/resources/IFEntityService.wsdl",
                  targetNamespace = "http://service.ws.vip.apps.new1step.com.au/") 
public class IFEntityServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ws.vip.apps.new1step.com.au/", "IFEntityServiceService");
    public final static QName IFEntityServicePort = new QName("http://service.ws.vip.apps.new1step.com.au/", "IFEntityServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/andy/workspaces/alw-web-apps/dongnanVipService/src/main/resources/IFEntityService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IFEntityServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/andy/workspaces/alw-web-apps/dongnanVipService/src/main/resources/IFEntityService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IFEntityServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IFEntityServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IFEntityServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IFEntityServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IFEntityServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IFEntityServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns IFEntityService
     */
    @WebEndpoint(name = "IFEntityServicePort")
    public IFEntityService getIFEntityServicePort() {
        return super.getPort(IFEntityServicePort, IFEntityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IFEntityService
     */
    @WebEndpoint(name = "IFEntityServicePort")
    public IFEntityService getIFEntityServicePort(WebServiceFeature... features) {
        return super.getPort(IFEntityServicePort, IFEntityService.class, features);
    }

}
